### ISSUE TITLE
Choose between data class versus regular class for JPA

### ISSUE THREAD

**Issue by sdeleuze** [spring-guides/tut-spring-boot-kotlin#12]
The tutorial currently suggests to use data classes which is handy but with JPA/Hibernate (see https://kotlinexpertise.com/hibernate-with-kotlin-spring-boot/) this is a design choice that could be discussed.

I think we should discuss this with Spring Data team to provide clear JPA/Hibernate guideline on this tricky question, and update this tutorial accordingly if needed.

cc @olivergierke @mp911de @s1monw1

**Comment by s1monw1** [comment]
Hi, 

I was about to ping you about my findings because I obviously used your guide as a reference and saw the use of data classes. This definitely needs to be discussed, and I'd be very interested in what the Data team says :) @mp911de and I already discussed the `AbstractPersistable` a bit (which I also adjusted according to the Hibernate dcumentation that suggests to yield constant values from `hashCode`).

Cheers

**Comment by sdeleuze** [comment]
FYI, I plan to migrate this tutorial to Spring Data JDBC instead of JPA, see #17.

**Comment by sdeleuze** [comment]
After more discussion with the Spring Data team, my conclusion is that JPA is just not a good fit in term of mindset with JPA, so I close this issue in favor of #17.
